# Generated by Django 5.2.1 on 2025-12-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denbotuser',
            name='login_otp',
        ),
        migrations.RemoveField(
            model_name='denbotuser',
            name='login_otp_set',
        ),
    ]
