# Generated by Django 5.2.1 on 2025-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_denbotuser_login_otp_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='denbotuser',
            index=models.Index(fields=['id'], name='user_id_idx'),
        ),
    ]
