# Generated by Django 5.2.1 on 2025-05-27 02:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenbotUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('login_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('login_otp_set', models.DateTimeField(blank=True, null=True, verbose_name='Login OTP Set Date/Time')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='user_phone_idx')],
            },
        ),
    ]
